language: java
jdk:
  - openjdk8
services:
  - docker

# env:
#   global:
#     secure: DOCKER_USER
#     secure: DOCKER_PASS

# replace the following env configurations with your own
env:
  global:
    - secure: nS72tiqkiKufVH2bapGtmAyWto8MVGMXvUmxnzpopYyy/VBh+NRjQ7oFt6pmkXejoavcTQrbiCqjoK9p29HnHguMXl4b8IqVDoYSGp0pR/AvPu9a8+UDsr5klWnwI3vednuzMA7EOstetiBVwvkF8Wxq/vhxfQh8H4PIgxlsf4NsbpTA6WLMrB8zHc6lKnASxcNkBtnMNhHiCA+tTOpb9S3GSH6GMbW3+O6G4+ZN0d0VjX6Pz+G3755cGgB43Y7oiuWPqrL7xoto5b7+ieTBlhiAdKW6lK9c0eAB6oYwdEiSK6zNshHzV19kJpYHy0P+REtPf9Uff8lO5zquhml0qzat/PcFL8HRhIfa8aAphuUUh6isytGfnZKLiFCbyNQwiCv6xfM3BzF3wDnwzBKHfTkLDJYF1Z4pOMG7Vw2t24WrtoJL1l+gMdG0UnA/hEh8x/Hb5hPOOlZpY/NYRmH/lEcQtE+nl4NVlb7u8NqOePLgx9rNESm9bwyS/PpbVaKmr1mXbLQVQEb0nXgg6V3CE+VmykykBy/n/IOuI+BdI0fOmGDqQgvq+wfbo2XWRPk97tm5xqwWWBnW6zS/tK0WSgv1r0EA7Am0nvLVcOxfTyu+Oqy04AMQSG8PoReNeZ636Cmou1AHzC/kgFZrZ08aSpt1JbrNy0JtFcXYbqDxldA=
    - secure: HaDl2lveLl7V8qegnalt7hkngMiNVJ+fuPJUvE9yWuVBbUnjX4QekOOKtc0bABJpTx6nb6YQD5zEsvcYmT3JGbZVNNl2yrNRTae65nCh9z6P1VuUW7HAcA76NAlE5OT2l+lm9GIP97Q89Xn1iL9LmSxlm1LT/AD9DIMJDdhBLPdLuMWOgKHeZiG6RlVn/LwmYf2A/MLRF6tulV4r/9c8Dji2/hrpUAjzaKoGkO+sEHpcec5QL8DdHiBbroUECm1qC4guMJmgBwX+yyjXlxFfKrK5noD46WdKzpmSC5WeNNT94kHMyHCyJOs/izlgYsfMaY5k/l08G09l4PmhHYn3vRZHLJDb+6x/t93QUmjqsh7EhYcW92MnS0Qy9OC4xeE3cTBfbOeOBFGY6XWVEpKy4ddrBkq+VoodEJ8b2UXDjJBoiNCYj8MvL1mpPmJ8zbYvbSzYQbpXGAjX58mD2kA4L3rTazYxTi5BfHUO2uWHfgncjHygX39g+7+RDH460xG6DUA1LnNNQ2rLI4JFx7Kxe4an4Qg/NglLVjMrRGNu/Luyx/NgLqa2w5ad/G0QU9TxfFzy8oPq97PmeJY4O3ddP7eUWRpxIq3avjVyAURg/wuS75m5IPLkcZj5qms+WymHY24O571AMwkgiJ3kH/XI+OuXXPApI7keulhJAtx05fk=

before_install:
  - docker pull openjdk:8-jdk-alpine

# Test & Build SpringBoot app
script:
  - mvn test
  - mvn clean package
  # Create Docker image for our app and push it to Dockerhub repository
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t travis-demo .
  - docker images
  - docker tag travis-demo interviewdot/travis-demo
  - docker push interviewdot/travis-demo

# Send the message of success after the docker image is pushed to dockerhub
notifications:
  email:
    - interviewdot@gmail.com