language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - docker pull openjdk:8-jdk-alpine

# Test & Build SpringBoot app
script:
  - mvn test
  - mvn clean package
  # Create Docker image for our app and push it to Dockerhub repository
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t travis-demo .
  - docker images
  - docker tag travis-demo mukesh9092/travis-demo
  - docker push mukesh9092/travis-demo

# Send the message of success after the docker image is pushed to dockerhub
notifications:
  email:
    - mukesh98thakur@gmail.com


